// Tables de traduction (issues de l'ancien moteur Python).

pub const INVOICE_TYPES: &[(&str, &str)] = &[
    ("380", "Facture"),
    ("303", "Facture"),
    ("270", "Facture"),
    ("203", "Avoir"),
    ("261", "Avoir"),
    ("262", "Avoir"),
    ("264", "Avoir"),
    ("200", "Proforma"),
    ("273", "Proforma"),
    ("210", "Facture de services"),
    ("212", "Facture simplifiée"),
    ("214", "Facture simplifiée (sans TVA)"),
    ("217", "Avoir (crédit)"),
    ("218", "Avoir (débit)"),
    ("220", "Avoir de services"),
    ("224", "Avoir de services (crédit)"),
    ("256", "Facture de services"),
    ("257", "Facture de services simplifiée"),
    ("274", "Facture de services"),
    ("275", "Facture simplifiée"),
    ("277", "Facture de services (sans TVA)"),
];

// UNCL4461 : https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL4461/
pub const PAYMENT_MODES: &[(&str, &str)] = &[
    ("10", "Espèces"),
    ("20", "Chèque"),
    ("30", "Virement"),
    ("42", "Paiement sur compte bancaire"),
    ("45", "Virement bancaire référencé"),
    ("48", "Carte bancaire"),
    ("49", "Prélèvement"),
    ("58", "Virement SEPA"),
    ("59", "Prélèvement SEPA"),
    ("68", "Paiement en ligne"),
    ("98", "Autre"),
];

pub const TAX_CATEGORIES: &[(&str, &str)] = &[
    ("S", "TVA standard"),
    ("Z", "TVA 0 %"),
    ("E", "Livraison intracommunautaire"),
    ("G", "TVA 0 % (autoliquidée)"),
    ("K", "TTF"),
    ("L", "Exonéré"),
    ("O", "Non soumis à la TVA"),
    ("A", "Autre"),
];

pub const UNITS: &[(&str, &str)] = &[
    ("H87", "pièce"),
    ("EA", "unité"),
    ("PCE", "pièce"),
    ("C62", "ensemble"),
    ("KGM", "kg"),
    ("GRM", "g"),
    ("MTR", "m"),
    ("MTR2", "m²"),
    ("MTR3", "m³"),
    ("CMTR", "cm"),
    ("LTR", "L"),
    ("DAY", "jour"),
    ("WEE", "semaine"),
    ("MON", "mois"),
    ("ANN", "an"),
    ("HRS", "heure"),
    ("KWH", "kWh"),
    ("MTK", "km"),
];

pub const PROFILES_UBL: &[(&str, &str)] = &[
    ("S1", "Essentiel"),
    ("S2", "Confort"),
    ("S3", "Extended"),
    ("S4", "Enrichi"),
];

pub const PROFILES_CII: &[(&str, &str)] = &[
    ("urn:cen.eu:en16931:2017#en16931#comfort", "Confort"),
    ("urn:cen.eu:en16931:2017#en16931#essential", "Essentiel"),
    ("urn:cen.eu:en16931:2017#en16931#extended", "Extended"),
    ("urn:cen.eu:en16931:2017", "EN 16931"),
];

/// (parent local, etiquette, libelle)
pub const TITLES: &[(&str, &str, &str)] = &[
    ("Invoice", "CustomizationID", "Norme (CustomizationID)"),
    ("CreditNote", "CustomizationID", "Norme (CustomizationID)"),
    ("Invoice", "ProfileID", "Profil"),
    ("CreditNote", "ProfileID", "Profil"),
    ("Invoice", "ID", "N° de facture"),
    ("CreditNote", "ID", "N° d'avoir"),
    ("Invoice", "IssueDate", "Date d'émission"),
    ("CreditNote", "IssueDate", "Date d'émission"),
    ("Invoice", "DueDate", "Date d'échéance"),
    ("CreditNote", "DueDate", "Date d'échéance"),
    ("Invoice", "InvoiceTypeCode", "Type de facture"),
    ("CreditNote", "CreditNoteTypeCode", "Type d'avoir"),
    ("Invoice", "Note", "Note / mention"),
    ("CreditNote", "Note", "Note / mention"),
    ("Invoice", "DocumentCurrencyCode", "Devise du document"),
    ("CreditNote", "DocumentCurrencyCode", "Devise du document"),
    ("Invoice", "AccountingCost", "Référence comptable interne"),
    ("CreditNote", "AccountingCost", "Référence comptable interne"),
    ("Invoice", "BuyerReference", "Référence acheteur"),
    ("CreditNote", "BuyerReference", "Référence acheteur"),
    ("Invoice", "SellerOrderReferencedDocumentID", "Réf. de commande vendeur"),
    ("Invoice", "BuyerOrderReferencedDocumentID", "Réf. de commande acheteur"),
    ("Invoice", "BilledCustomerID", "Référence client facture"),
    ("InvoicePeriod", "StartDate", "Période : début"),
    ("InvoicePeriod", "EndDate", "Période : fin"),
    ("InvoicePeriod", "DescriptionCode", "Période : code de description"),
    ("OrderReference", "ID", "N° de commande"),
    ("OrderReference", "SalesOrderID", "Réf. de commande client"),
    ("OrderReference", "IssueDate", "Date de la commande"),
    ("OrderReference", "LineID", "Ligne de commande"),
    ("ContractDocumentReference", "ID", "Référence de contrat"),
    ("AdditionalDocumentReference", "ID", "Référence de document complémentaire"),
    ("BillingReference", "ID", "Référence facture anterieure"),
    ("BillingReference", "LineID", "Ligne de la facture anterieure"),
    ("Party", "EndpointID", "Identifiant d'émetteur"),
    ("Party", "MarkingID", "Référence interne"),
    ("PartyName", "Name", "Raison sociale"),
    ("PostalAddress", "StreetName", "Rue"),
    ("PostalAddress", "CityName", "Ville"),
    ("PostalAddress", "PostalZone", "Code postal"),
    ("PostalAddress", "CountrySubentity", "Département / Région"),
    ("PostalAddress", "AdditionalStreetName", "Complément d'adresse"),
    ("Country", "IdentificationCode", "Pays"),
    ("PartyTaxScheme", "CompanyID", "N° de TVA"),
    ("PartyLegalEntity", "RegistrationName", "Dénomination légale"),
    ("PartyLegalEntity", "CompanyID", "Identifiant registre (SIREN)"),
    ("PartyLegalEntity", "RegistrationID", "Identifiant d'enregistrement"),
    ("PartyIdentification", "ID", "Identifiant de la partie"),
    ("Contact", "Name", "Nom du contact"),
    ("Contact", "Telephone", "Téléphone"),
    ("Contact", "ElectronicMail", "E-mail"),
    ("Person", "FullName", "Nom complet"),
    ("Delivery", "ActualDeliveryDate", "Date de livraison"),
    ("Delivery", "RequestedDeliveryDate", "Livraison demandée"),
    ("Delivery", "DespatchAdviceDate", "Date d'expédition"),
    ("Address", "StreetName", "Rue"),
    ("Address", "CityName", "Ville"),
    ("Address", "PostalZone", "Code postal"),
    ("Address", "CountrySubentity", "Département / Région"),
    ("Address", "AdditionalStreetName", "Complément d'adresse"),
    ("PaymentMeans", "PaymentMeansCode", "Mode de paiement"),
    ("PaymentMeans", "PaymentID", "Référence de paiement"),
    ("PaymentMeans", "PaymentMandateID", "Référence mandat SEPA"),
    ("PayeeFinancialAccount", "ID", "IBAN"),
    ("PayeeFinancialAccount", "Name", "Titre du compte"),
    ("FinancialInstitutionBranch", "ID", "BIC"),
    ("FinancialInstitutionBranch", "Name", "Nom de la banque"),
    ("FinancialInstitution", "Name", "Nom de la banque"),
    ("PaymentTerms", "Note", "Conditions de paiement"),
    ("PaymentTerms", "AmountDueDate", "Montant dû à l'échéance"),
    ("PaymentTerms", "Amount", "Montant de l'échéance"),
    ("PaymentTerms", "DueDate", "Date d'échéance"),
    ("TaxTotal", "TaxAmount", "Total TVA"),
    ("TaxSubtotal", "TaxableAmount", "Base de calcul TVA"),
    ("TaxSubtotal", "TaxAmount", "Montant TVA"),
    ("TaxCategory", "ID", "Catégorie de TVA"),
    ("TaxCategory", "Percent", "Taux de TVA"),
    ("TaxScheme", "ID", "Régime de TVA"),
    ("AllowanceBasis", "AllowanceReasonCode", "Motif de la remise"),
    ("AllowanceBasis", "AllowanceReason", "Description de la remise"),
    ("AllowanceBasis", "SequenceNumeric", "Numéro de remise"),
    ("ChargeBasis", "ChargeReasonCode", "Motif de la majoration"),
    ("ChargeBasis", "ChargeReason", "Description de la majoration"),
    ("ChargeBasis", "SequenceNumeric", "Numéro de majoration"),
    ("Allowance", "AllowanceReasonCode", "Motif remise globale"),
    ("Allowance", "AllowanceReason", "Description remise globale"),
    ("Allowance", "AllowanceAmount", "Montant de la remise"),
    ("Allowance", "RatePercent", "Taux de la remise"),
    ("Charge", "ChargeReasonCode", "Motif majoration globale"),
    ("Charge", "ChargeReason", "Description majoration globale"),
    ("Charge", "ChargeAmount", "Montant de la majoration"),
    ("Charge", "RatePercent", "Taux de la majoration"),
    ("LegalMonetaryTotal", "LineExtensionAmount", "Total lignes (HT)"),
    ("LegalMonetaryTotal", "TaxExclusiveAmount", "Total HT"),
    ("LegalMonetaryTotal", "TaxInclusiveAmount", "Total TTC"),
    ("LegalMonetaryTotal", "TaxSubtotalTaxableAmount", "Base TVA"),
    ("LegalMonetaryTotal", "TaxSubtotalTaxAmount", "Montant TVA"),
    ("LegalMonetaryTotal", "AllowanceTotalAmount", "Remises totales"),
    ("LegalMonetaryTotal", "ChargeTotalAmount", "Majorations totales"),
    ("LegalMonetaryTotal", "PrepaidAmount", "Montant prépayé"),
    ("LegalMonetaryTotal", "PayableRoundingAmount", "Arrondi"),
    ("LegalMonetaryTotal", "PayableAmount", "Montant à payer"),
    ("InvoiceLine", "ID", "N° de ligne"),
    ("CreditNoteLine", "ID", "N° de ligne"),
    ("InvoiceLine", "Note", "Note de la ligne"),
    ("CreditNoteLine", "Note", "Note de la ligne"),
    ("InvoiceLine", "InvoicedQuantity", "Quantité"),
    ("CreditNoteLine", "InvoicedQuantity", "Quantité"),
    ("InvoiceLine", "LineExtensionAmount", "Total de la ligne (HT)"),
    ("CreditNoteLine", "LineExtensionAmount", "Total de la ligne (HT)"),
    ("OrderLineReference", "LineID", "Ligne de commande"),
    ("Item", "Description", "Description de l'article"),
    ("Item", "Name", "Désignation de l'article"),
    ("Item", "ModelID", "Modèle"),
    ("Item", "CommodityCode", "Code douanier"),
    ("Item", "StandardID", "Code normalisé article"),
    ("SellersItemIdentification", "ID", "Référence article (vendeur)"),
    ("BuyersItemIdentification", "ID", "Référence article (acheteur)"),
    ("ManufacturersItemIdentification", "ID", "Référence article (fabricant)"),
    ("ItemIdentification", "ID", "Référence article"),
    ("ClassifiedTaxCategory", "ID", "Catégorie de TVA"),
    ("ClassifiedTaxCategory", "Percent", "Taux de TVA"),
    ("AdditionalItemProperty", "Name", "Propriété de l'article"),
    ("AdditionalItemProperty", "Value", "Valeur de la propriété"),
    ("Price", "PriceAmount", "Prix unitaire (HT)"),
    ("Price", "BaseQuantity", "Quantité de base du prix"),
    ("Price", "AllowanceFactorPercent", "Remise sur le prix"),
    ("Price", "ChargeFactorPercent", "Majoration sur le prix"),
    ("ExchangedDocument", "ID", "N° de facture"),
    ("ExchangedDocument", "TypeCode", "Type de facture"),
    ("ExchangedDocument", "IssueDateTime", "Date d'émission"),
    ("ExchangedDocument", "DueDateDateTime", "Date d'échéance"),
    ("ExchangedDocument", "DocumentCurrencyCode", "Devise"),
    ("ExchangedDocument", "Note", "Note / mention"),
    ("ExchangedDocument", "LineCountNumeric", "Nombre de lignes"),
    ("ExchangedDocument", "Description", "Description du document"),
    ("Line", "ID", "Réf. de commande"),
    ("Line", "Name", "Nom (référence acheteur)"),
    ("IncludedPeriod", "StartDateTime", "Période : début"),
    ("IncludedPeriod", "EndDateTime", "Période : fin"),
    ("GuidelineSpecifiedDocumentContextParameter", "ID", "Profil"),
    ("Seller", "Name", "Raison sociale (vendeur)"),
    ("Buyer", "Name", "Raison sociale (acheteur)"),
    ("SpecifiedLogisticsSupplier", "Name", "Destinataire / transporteur"),
    ("PostalTradeAddress", "LineOne", "Rue"),
    ("PostalTradeAddress", "LineTwo", "Complément d'adresse"),
    ("PostalTradeAddress", "CityName", "Ville"),
    ("PostalTradeAddress", "Postcode", "Code postal"),
    ("PostalTradeAddress", "CountrySubentity", "Département / Région"),
    ("PostalTradeAddress", "CountryID", "Pays"),
    ("PostalTradeAddress", "CountryName", "Pays (nom)"),
    ("SpecifiedTaxRegistration", "ID", "N° de TVA"),
    ("SpecifiedLegalOrganization", "ID", "Identifiant légal (SIREN)"),
    ("DefinedTradeContact", "PersonName", "Nom du contact"),
    ("DefinedTradeContact", "TelephoneNumber", "Téléphone"),
    ("DefinedTradeContact", "ElectronicMail", "E-mail"),
    ("ActualSupplyChainEvent", "OccurrenceDateTime", "Date de livraison"),
    ("PaymentMeans", "TypeCode", "Mode de paiement"),
    ("PayeePartyCreditAccount", "ID", "IBAN"),
    ("SpecifiedTradePaymentTerms", "Description", "Conditions de paiement"),
    ("SpecifiedTradePaymentTerms", "DueDateDateTime", "Date d'échéance"),
    ("SpecifiedTradePaymentTerms", "Amount", "Montant à l'échéance"),
    ("ApplicableTradeTax", "CalculatedAmount", "Montant de TVA"),
    ("ApplicableTradeTax", "TypeCode", "Nature de la taxe"),
    ("ApplicableTradeTax", "RateApplicablePercent", "Taux de TVA"),
    ("CategoryTradeTax", "TypeCode", "Catégorie de TVA"),
    ("CategoryTradeTax", "RateApplicablePercent", "Taux de TVA"),
    ("ApplicableTradeSettlement", "InvoiceCurrencyCode", "Devise de règlement"),
    ("ApplicableTradeSettlement", "LineTotalAmount", "Total HT"),
    ("ApplicableTradeSettlement", "TotalAmount", "Total TTC"),
    ("ApplicableTradeSettlement", "DuePayableAmount", "Montant à payer"),
    ("ApplicableTradeSettlement", "PrepaidAmount", "Montant prépayé"),
    ("SpecifiedTradeLineItem", "LineID", "N° de ligne"),
    ("SpecifiedTradeLineItem", "Name", "Désignation"),
    ("SpecifiedTradeLineItem", "Description", "Description"),
    ("SpecifiedTradeLineItem", "LineStatusCode", "Statut de la ligne"),
    ("DefinedTradeProduct", "SellerAssignedID", "Référence article (vendeur)"),
    ("DefinedTradeProduct", "BuyerAssignedID", "Référence article (acheteur)"),
    ("DefinedTradeProduct", "Description", "Description du produit"),
    ("GrossPrice", "ChargeAmount", "P.U. TTC"),
    ("NetPrice", "ChargeAmount", "P.U. HT"),
    ("SpecifiedLineTradeTransaction", "InvoicedQuantity", "Quantité"),
    ("SpecifiedLineTradeTransaction", "LineExtensionAmount", "Total de la ligne (HT)"),
    ("SpecifiedLineTradeTransaction", "BasisQuantity", "Quantité de base"),
    ("SpecifiedPeriod", "StartDateTime", "Période ligne : début"),
    ("SpecifiedPeriod", "EndDateTime", "Période ligne : fin"),
    ("SpecifiedLineTradeSettlement", "CalculatedAmount", "TVA de la ligne"),
    ("SpecifiedLineTradeSettlement", "TypeCode", "Nature de la taxe"),
    ("SpecifiedLineTradeSettlement", "BasisAmount", "Base de TVA"),
    ("DesignatedPropertyTradeAttribute", "Name", "Propriété"),
    ("DesignatedPropertyTradeAttribute", "Value", "Valeur de la propriété"),
    ("BuyerOrderReferencedLine", "ID", "Ligne de commande (acheteur)"),
    ("SellerOrderReferencedLine", "ID", "Ligne de commande (vendeur)"),
    ("AssociatedDocumentLineDocument", "LineID", "N° de ligne"),
    ("SpecifiedTradeProduct", "Name", "Désignation"),
    ("SpecifiedTradeProduct", "Description", "Description"),
    ("SpecifiedTradeProduct", "SellerAssignedID", "Référence article (vendeur)"),
    ("SpecifiedTradeProduct", "BuyerAssignedID", "Référence article (acheteur)"),
    ("ApplicableProductCharacteristic", "Description", "Caractéristique"),
    ("ApplicableProductCharacteristic", "Value", "Valeur de la caractéristique"),
    ("IncludedNote", "Content", "Note"),
    ("SpecifiedLineTradeDelivery", "BilledQuantity", "Quantité"),
    ("NetPriceProductTradePrice", "ChargeAmount", "P.U. HT"),
    ("GrossPriceProductTradePrice", "ChargeAmount", "P.U. TTC"),
    ("AppliedTradeAllowanceCharge", "ActualAmount", "Frais / remise"),
    ("SpecifiedTradeSettlementLineMonetarySummation", "LineTotalAmount", "Total de la ligne (HT)"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "LineTotalAmount", "Total des lignes (HT)"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "TaxBasisTotalAmount", "Total HT"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "TaxTotalAmount", "Montant de TVA"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "GrandTotalAmount", "Total TTC"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "TotalPrepaidAmount", "Montant prépayé"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "DuePayableAmount", "Montant à payer"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "RoundingAmount", "Arrondi"),
    ("SpecifiedTradeSettlementPaymentMeans", "TypeCode", "Mode de paiement"),
    ("SpecifiedTradeSettlementPaymentMeans", "Information", "Information paiement"),
    ("PayeePartyCreditorFinancialAccount", "IBANID", "IBAN"),
    ("PayeePartyCreditorFinancialAccount", "AccountName", "Titre du compte"),
    ("PayeeSpecifiedCreditorFinancialInstitution", "BICID", "BIC"),
    ("SellerTradeParty", "Name", "Raison sociale (vendeur)"),
    ("BuyerTradeParty", "Name", "Raison sociale (acheteur)"),
    ("PostalTradeAddress", "PostcodeCode", "Code postal"),
    ("ApplicableHeaderTradeSettlement", "InvoiceCurrencyCode", "Devise de règlement"),
    ("ApplicableHeaderTradeSettlement", "CreditorReferenceID", "Référence créancier"),
    ("SpecifiedTradePaymentTerms", "DirectDebitMandateID", "Mandat SEPA"),
];

pub const TITLES_GENERIC: &[(&str, &str)] = &[
    ("ID", "Identifiant"),
    ("Name", "Nom"),
    ("Note", "Note"),
    ("Percent", "Taux (%)"),
    ("Value", "Valeur"),
    ("Description", "Description"),
    ("TypeCode", "Code type"),
    ("Date", "Date"),
    ("Amount", "Montant"),
    ("Quantity", "Quantité"),
    ("CurrencyCode", "Devise"),
    ("StreetName", "Rue"),
    ("CityName", "Ville"),
    ("PostalZone", "Code postal"),
    ("CountryID", "Pays"),
    ("CountrySubentity", "Département / Région"),
    ("ElectronicMail", "E-mail"),
    ("TelephoneNumber", "Téléphone"),
    ("LineOne", "Rue"),
    ("Postcode", "Code postal"),
    ("CalculatedAmount", "Montant calculé"),
    ("ChargeAmount", "Montant"),
    ("RateApplicablePercent", "Taux (%)"),
    ("OccurrenceDateTime", "Date"),
    ("StartDateTime", "Début"),
    ("EndDateTime", "Fin"),
    ("DueDateDateTime", "Échéance"),
    ("IssueDateTime", "Date d'émission"),
    ("SellerAssignedID", "Référence article"),
    ("BuyerAssignedID", "Référence article (acheteur)"),
    ("LineID", "N° de ligne"),
    ("LineExtensionAmount", "Total ligne"),
    ("InvoicedQuantity", "Quantité"),
    ("PriceAmount", "Prix"),
    ("BaseQuantity", "Base"),
    ("TaxableAmount", "Base"),
    ("TaxAmount", "Montant TVA"),
    ("PayableAmount", "À payer"),
    ("LineTotalAmount", "Total HT"),
    ("TotalAmount", "Total TTC"),
    ("DuePayableAmount", "À payer"),
    ("CustomizationID", "Norme"),
    ("ProfileID", "Profil"),
    ("IssueDate", "Date d'émission"),
    ("DueDate", "Échéance"),
    ("DocumentCurrencyCode", "Devise"),
    ("AccountingCost", "Réf. comptable"),
    ("PaymentMeansCode", "Mode de paiement"),
    ("PaymentID", "Réf. paiement"),
    ("CompanyID", "Identifiant société"),
    ("RegistrationName", "Dénomination légale"),
    ("IdentificationCode", "Pays"),
    ("EndpointID", "Identifiant émetteur"),
    ("ModelID", "Modèle"),
    ("StandardID", "Code normalisé"),
    ("CommodityCode", "Code douanier"),
    ("SequenceNumeric", "Séquence"),
    ("AllowanceReason", "Motif remise"),
    ("ChargeReason", "Motif majoration"),
    ("RatePercent", "Taux (%)"),
    ("AllowanceAmount", "Montant remise"),
    ("PrepaidAmount", "Prépayé"),
    ("PayableRoundingAmount", "Arrondi"),
    ("TaxInclusiveAmount", "Total TTC"),
    ("TaxExclusiveAmount", "Total HT"),
    ("LineCountNumeric", "Nombre de lignes"),
    ("BilledQuantity", "Quantité"),
    ("IBANID", "IBAN"),
    ("BICID", "BIC"),
    ("AccountName", "Titre du compte"),
    ("CreditorReferenceID", "Référence créancier"),
    ("DirectDebitMandateID", "Mandat SEPA"),
    ("GlobalID", "Identifiant global"),
    ("URIID", "URI"),
    ("Information", "Information"),
    ("ActualAmount", "Montant"),
    ("CategoryCode", "Catégorie"),
    ("ChargeIndicator", "Frais ou remise"),
    ("Indicator", "Indicateur"),
    ("SubjectCode", "Code sujet"),
    ("DateTimeString", "Date"),
    ("GrandTotalAmount", "Total TTC"),
    ("TaxBasisTotalAmount", "Total HT"),
    ("TaxTotalAmount", "Montant TVA"),
    ("TotalPrepaidAmount", "Montant prépayé"),
    ("RoundingAmount", "Arrondi"),
    ("BasisAmount", "Base"),
    ("InvoiceCurrencyCode", "Devise"),
    ("PostcodeCode", "Code postal"),
    ("PersonName", "Nom du contact"),
    ("DueDateTypeCode", "Type d'échéance"),
];
