// Tables de traduction (generees depuis l'ancien moteur Python).

pub const INVOICE_TYPES: &[(&str, &str)] = &[
    ("380", "Facture"),
    ("303", "Facture"),
    ("270", "Facture"),
    ("203", "Avoir"),
    ("261", "Avoir"),
    ("262", "Avoir"),
    ("264", "Avoir"),
    ("200", "Proforma"),
    ("273", "Proforma"),
    ("210", "Facture de services"),
    ("212", "Facture simplifiee"),
    ("214", "Facture simplifiee (sans TVA)"),
    ("217", "Avoir (credit)"),
    ("218", "Avoir (debit)"),
    ("220", "Avoir de services"),
    ("224", "Avoir de services (credit)"),
    ("256", "Facture de services"),
    ("257", "Facture de services simplifiee"),
    ("274", "Facture de services"),
    ("275", "Facture simplifiee"),
    ("277", "Facture de services (sans TVA)"),
];

pub const PAYMENT_MODES: &[(&str, &str)] = &[
    ("10", "Especes"),
    ("20", "Chque"),
    ("30", "Virement"),
    ("42", "Carte bancaire"),
    ("45", "Carte bancaire"),
    ("48", "Paiement en ligne"),
    ("58", "Premelement"),
    ("59", "Virement SEPA"),
    ("98", "Autre"),
];

pub const TAX_CATEGORIES: &[(&str, &str)] = &[
    ("S", "TVA standard"),
    ("Z", "TVA 0 %"),
    ("E", "Livraison intracommunautaire"),
    ("G", "TVA 0 % (autoliquide)"),
    ("K", "TTF"),
    ("L", "Exonere"),
    ("O", "Non soumis a la TVA"),
    ("A", "Autre"),
];

pub const UNITS: &[(&str, &str)] = &[
    ("H87", "piece"),
    ("EA", "unite"),
    ("PCE", "piece"),
    ("C62", "ensemble"),
    ("KGM", "kg"),
    ("GRM", "g"),
    ("MTR", "m"),
    ("MTR2", "m²"),
    ("MTR3", "m³"),
    ("CMTR", "cm"),
    ("LTR", "L"),
    ("DAY", "jour"),
    ("WEE", "semaine"),
    ("MON", "mois"),
    ("ANN", "an"),
    ("HRS", "heure"),
    ("KWH", "kWh"),
    ("MTK", "km"),
];

pub const PROFILES_UBL: &[(&str, &str)] = &[
    ("S1", "Essentiel"),
    ("S2", "Confort"),
    ("S3", "Extended"),
    ("S4", "Enrichi"),
];

pub const PROFILES_CII: &[(&str, &str)] = &[
    ("urn:cen.eu:en16931:2017#en16931#comfort", "Confort"),
    ("urn:cen.eu:en16931:2017#en16931#essential", "Essentiel"),
    ("urn:cen.eu:en16931:2017#en16931#extended", "Extended"),
    ("urn:cen.eu:en16931:2017", "EN 16931"),
];

/// (parent local, etiquette, libelle)
pub const TITLES: &[(&str, &str, &str)] = &[
    ("Invoice", "CustomizationID", "Norme (CustomizationID)"),
    ("CreditNote", "CustomizationID", "Norme (CustomizationID)"),
    ("Invoice", "ProfileID", "Profil"),
    ("CreditNote", "ProfileID", "Profil"),
    ("Invoice", "ID", "N° de facture"),
    ("CreditNote", "ID", "N° d'avoir"),
    ("Invoice", "IssueDate", "Date d'emission"),
    ("CreditNote", "IssueDate", "Date d'emission"),
    ("Invoice", "DueDate", "Date d'echance"),
    ("CreditNote", "DueDate", "Date d'echance"),
    ("Invoice", "InvoiceTypeCode", "Type de facture"),
    ("CreditNote", "CreditNoteTypeCode", "Type d'avoir"),
    ("Invoice", "Note", "Note / mention"),
    ("CreditNote", "Note", "Note / mention"),
    ("Invoice", "DocumentCurrencyCode", "Devise du document"),
    ("CreditNote", "DocumentCurrencyCode", "Devise du document"),
    ("Invoice", "AccountingCost", "Reference comptable interne"),
    ("CreditNote", "AccountingCost", "Reference comptable interne"),
    ("Invoice", "BuyerReference", "Reference acheteur"),
    ("CreditNote", "BuyerReference", "Reference acheteur"),
    ("Invoice", "SellerOrderReferencedDocumentID", "Ref. de commande vendeur"),
    ("Invoice", "BuyerOrderReferencedDocumentID", "Ref. de commande acheteur"),
    ("Invoice", "BilledCustomerID", "Reference client facture"),
    ("InvoicePeriod", "StartDate", "Periode : debut"),
    ("InvoicePeriod", "EndDate", "Periode : fin"),
    ("InvoicePeriod", "DescriptionCode", "Periode : code de description"),
    ("OrderReference", "ID", "N° de commande"),
    ("OrderReference", "SalesOrderID", "Ref. de commande client"),
    ("OrderReference", "IssueDate", "Date de la commande"),
    ("OrderReference", "LineID", "Ligne de commande"),
    ("ContractDocumentReference", "ID", "Reference de contrat"),
    ("AdditionalDocumentReference", "ID", "Reference de document complementaire"),
    ("BillingReference", "ID", "Reference facture anterieure"),
    ("BillingReference", "LineID", "Ligne de la facture anterieure"),
    ("Party", "EndpointID", "Identifiant d'emetteur"),
    ("Party", "MarkingID", "Reference interne"),
    ("PartyName", "Name", "Raison sociale"),
    ("PostalAddress", "StreetName", "Rue"),
    ("PostalAddress", "CityName", "Ville"),
    ("PostalAddress", "PostalZone", "Code postal"),
    ("PostalAddress", "CountrySubentity", "Departement / Region"),
    ("PostalAddress", "AdditionalStreetName", "Complement d'adresse"),
    ("Country", "IdentificationCode", "Pays"),
    ("PartyTaxScheme", "CompanyID", "N° de TVA"),
    ("PartyLegalEntity", "RegistrationName", "Denomination legale"),
    ("PartyLegalEntity", "CompanyID", "Identifiant registre (SIREN)"),
    ("PartyLegalEntity", "RegistrationID", "Identifiant d'enregistrement"),
    ("PartyIdentification", "ID", "Identifiant de la partie"),
    ("Contact", "Name", "Nom du contact"),
    ("Contact", "Telephone", "Telephone"),
    ("Contact", "ElectronicMail", "E-mail"),
    ("Person", "FullName", "Nom complet"),
    ("Delivery", "ActualDeliveryDate", "Date de livraison"),
    ("Delivery", "RequestedDeliveryDate", "Livraison demandee"),
    ("Delivery", "DespatchAdviceDate", "Date d'expedition"),
    ("Address", "StreetName", "Rue"),
    ("Address", "CityName", "Ville"),
    ("Address", "PostalZone", "Code postal"),
    ("Address", "CountrySubentity", "Departement / Region"),
    ("Address", "AdditionalStreetName", "Complement d'adresse"),
    ("PaymentMeans", "PaymentMeansCode", "Mode de paiement"),
    ("PaymentMeans", "PaymentID", "Reference de paiement"),
    ("PaymentMeans", "PaymentMandateID", "Reference mandat SEPA"),
    ("PayeeFinancialAccount", "ID", "IBAN"),
    ("PayeeFinancialAccount", "Name", "Titre du compte"),
    ("FinancialInstitutionBranch", "ID", "BIC"),
    ("FinancialInstitutionBranch", "Name", "Nom de la banque"),
    ("FinancialInstitution", "Name", "Nom de la banque"),
    ("PaymentTerms", "Note", "Conditions de paiement"),
    ("PaymentTerms", "AmountDueDate", "Montant du a l'echance"),
    ("PaymentTerms", "Amount", "Montant de l'echance"),
    ("PaymentTerms", "DueDate", "Date d'echance"),
    ("TaxTotal", "TaxAmount", "Total TVA"),
    ("TaxSubtotal", "TaxableAmount", "Base de calcul TVA"),
    ("TaxSubtotal", "TaxAmount", "Montant TVA"),
    ("TaxCategory", "ID", "Categorie de TVA"),
    ("TaxCategory", "Percent", "Taux de TVA"),
    ("TaxScheme", "ID", "Regime de TVA"),
    ("AllowanceBasis", "AllowanceReasonCode", "Motif de la remise"),
    ("AllowanceBasis", "AllowanceReason", "Description de la remise"),
    ("AllowanceBasis", "SequenceNumeric", "Numero de remise"),
    ("ChargeBasis", "ChargeReasonCode", "Motif de la majoration"),
    ("ChargeBasis", "ChargeReason", "Description de la majoration"),
    ("ChargeBasis", "SequenceNumeric", "Numero de majoration"),
    ("Allowance", "AllowanceReasonCode", "Motif remise globale"),
    ("Allowance", "AllowanceReason", "Description remise globale"),
    ("Allowance", "AllowanceAmount", "Montant de la remise"),
    ("Allowance", "RatePercent", "Taux de la remise"),
    ("Charge", "ChargeReasonCode", "Motif majoration globale"),
    ("Charge", "ChargeReason", "Description majoration globale"),
    ("Charge", "ChargeAmount", "Montant de la majoration"),
    ("Charge", "RatePercent", "Taux de la majoration"),
    ("LegalMonetaryTotal", "LineExtensionAmount", "Total lignes (HT)"),
    ("LegalMonetaryTotal", "TaxExclusiveAmount", "Total HT"),
    ("LegalMonetaryTotal", "TaxInclusiveAmount", "Total TTC"),
    ("LegalMonetaryTotal", "TaxSubtotalTaxableAmount", "Base TVA"),
    ("LegalMonetaryTotal", "TaxSubtotalTaxAmount", "Montant TVA"),
    ("LegalMonetaryTotal", "AllowanceTotalAmount", "Remises totales"),
    ("LegalMonetaryTotal", "ChargeTotalAmount", "Majorations totales"),
    ("LegalMonetaryTotal", "PrepaidAmount", "Montant prepaye"),
    ("LegalMonetaryTotal", "PayableRoundingAmount", "Arrondi"),
    ("LegalMonetaryTotal", "PayableAmount", "Montant a payer"),
    ("InvoiceLine", "ID", "N° de ligne"),
    ("CreditNoteLine", "ID", "N° de ligne"),
    ("InvoiceLine", "Note", "Note de la ligne"),
    ("CreditNoteLine", "Note", "Note de la ligne"),
    ("InvoiceLine", "InvoicedQuantity", "Quantite"),
    ("CreditNoteLine", "InvoicedQuantity", "Quantite"),
    ("InvoiceLine", "LineExtensionAmount", "Total de la ligne (HT)"),
    ("CreditNoteLine", "LineExtensionAmount", "Total de la ligne (HT)"),
    ("OrderLineReference", "LineID", "Ligne de commande"),
    ("Item", "Description", "Description de l'article"),
    ("Item", "Name", "Designation de l'article"),
    ("Item", "ModelID", "Modele"),
    ("Item", "CommodityCode", "Code douanier"),
    ("Item", "StandardID", "Code normalise article"),
    ("SellersItemIdentification", "ID", "Reference article (vendeur)"),
    ("BuyersItemIdentification", "ID", "Reference article (acheteur)"),
    ("ManufacturersItemIdentification", "ID", "Reference article (fabricant)"),
    ("ItemIdentification", "ID", "Reference article"),
    ("ClassifiedTaxCategory", "ID", "Categorie de TVA"),
    ("ClassifiedTaxCategory", "Percent", "Taux de TVA"),
    ("AdditionalItemProperty", "Name", "Propriete de l'article"),
    ("AdditionalItemProperty", "Value", "Valeur de la propriete"),
    ("Price", "PriceAmount", "Prix unitaire (HT)"),
    ("Price", "BaseQuantity", "Quantite de base du prix"),
    ("Price", "AllowanceFactorPercent", "Remise sur le prix"),
    ("Price", "ChargeFactorPercent", "Majoration sur le prix"),
    ("ExchangedDocument", "ID", "N° de facture"),
    ("ExchangedDocument", "TypeCode", "Type de facture"),
    ("ExchangedDocument", "IssueDateTime", "Date d'emission"),
    ("ExchangedDocument", "DueDateDateTime", "Date d'echance"),
    ("ExchangedDocument", "DocumentCurrencyCode", "Devise"),
    ("ExchangedDocument", "Note", "Note / mention"),
    ("ExchangedDocument", "LineCountNumeric", "Nombre de lignes"),
    ("ExchangedDocument", "Description", "Description du document"),
    ("Line", "ID", "Ref. de commande"),
    ("Line", "Name", "Nom (reference acheteur)"),
    ("IncludedPeriod", "StartDateTime", "Periode : debut"),
    ("IncludedPeriod", "EndDateTime", "Periode : fin"),
    ("GuidelineSpecifiedDocumentContextParameter", "ID", "Profil"),
    ("Seller", "Name", "Raison sociale (vendeur)"),
    ("Buyer", "Name", "Raison sociale (acheteur)"),
    ("SpecifiedLogisticsSupplier", "Name", "Destinataire / transporteur"),
    ("PostalTradeAddress", "LineOne", "Rue"),
    ("PostalTradeAddress", "LineTwo", "Complement d'adresse"),
    ("PostalTradeAddress", "CityName", "Ville"),
    ("PostalTradeAddress", "Postcode", "Code postal"),
    ("PostalTradeAddress", "CountrySubentity", "Departement / Region"),
    ("PostalTradeAddress", "CountryID", "Pays"),
    ("PostalTradeAddress", "CountryName", "Pays (nom)"),
    ("SpecifiedTaxRegistration", "ID", "N° de TVA"),
    ("SpecifiedLegalOrganization", "ID", "Identifiant legal (SIREN)"),
    ("DefinedTradeContact", "PersonName", "Nom du contact"),
    ("DefinedTradeContact", "TelephoneNumber", "Telephone"),
    ("DefinedTradeContact", "ElectronicMail", "E-mail"),
    ("ActualSupplyChainEvent", "OccurrenceDateTime", "Date de livraison"),
    ("PaymentMeans", "TypeCode", "Mode de paiement"),
    ("PayeePartyCreditAccount", "ID", "IBAN"),
    ("SpecifiedTradePaymentTerms", "Description", "Conditions de paiement"),
    ("SpecifiedTradePaymentTerms", "DueDateDateTime", "Date d'echance"),
    ("SpecifiedTradePaymentTerms", "Amount", "Montant a l'echance"),
    ("ApplicableTradeTax", "CalculatedAmount", "Montant de TVA"),
    ("ApplicableTradeTax", "TypeCode", "Nature de la taxe"),
    ("ApplicableTradeTax", "RateApplicablePercent", "Taux de TVA"),
    ("CategoryTradeTax", "TypeCode", "Categorie de TVA"),
    ("CategoryTradeTax", "RateApplicablePercent", "Taux de TVA"),
    ("ApplicableTradeSettlement", "InvoiceCurrencyCode", "Devise de reglement"),
    ("ApplicableTradeSettlement", "LineTotalAmount", "Total HT"),
    ("ApplicableTradeSettlement", "TotalAmount", "Total TTC"),
    ("ApplicableTradeSettlement", "DuePayableAmount", "Montant a payer"),
    ("ApplicableTradeSettlement", "PrepaidAmount", "Montant prepaye"),
    ("SpecifiedTradeLineItem", "LineID", "N° de ligne"),
    ("SpecifiedTradeLineItem", "Name", "Designation"),
    ("SpecifiedTradeLineItem", "Description", "Description"),
    ("SpecifiedTradeLineItem", "LineStatusCode", "Statut de la ligne"),
    ("DefinedTradeProduct", "SellerAssignedID", "Reference article (vendeur)"),
    ("DefinedTradeProduct", "BuyerAssignedID", "Reference article (acheteur)"),
    ("DefinedTradeProduct", "Description", "Description du produit"),
    ("GrossPrice", "ChargeAmount", "P.U. TTC"),
    ("NetPrice", "ChargeAmount", "P.U. HT"),
    ("SpecifiedLineTradeTransaction", "InvoicedQuantity", "Quantite"),
    ("SpecifiedLineTradeTransaction", "LineExtensionAmount", "Total de la ligne (HT)"),
    ("SpecifiedLineTradeTransaction", "BasisQuantity", "Quantite de base"),
    ("SpecifiedPeriod", "StartDateTime", "Periode ligne : debut"),
    ("SpecifiedPeriod", "EndDateTime", "Periode ligne : fin"),
    ("SpecifiedLineTradeSettlement", "CalculatedAmount", "TVA de la ligne"),
    ("SpecifiedLineTradeSettlement", "TypeCode", "Nature de la taxe"),
    ("SpecifiedLineTradeSettlement", "BasisAmount", "Base de TVA"),
    ("DesignatedPropertyTradeAttribute", "Name", "Propriete"),
    ("DesignatedPropertyTradeAttribute", "Value", "Valeur de la propriete"),
    ("BuyerOrderReferencedLine", "ID", "Ligne de commande (acheteur)"),
    ("SellerOrderReferencedLine", "ID", "Ligne de commande (vendeur)"),
    ("AssociatedDocumentLineDocument", "LineID", "N° de ligne"),
    ("SpecifiedTradeProduct", "Name", "Designation"),
    ("SpecifiedTradeProduct", "Description", "Description"),
    ("SpecifiedTradeProduct", "SellerAssignedID", "Reference article (vendeur)"),
    ("SpecifiedTradeProduct", "BuyerAssignedID", "Reference article (acheteur)"),
    ("ApplicableProductCharacteristic", "Description", "Caracteristique"),
    ("ApplicableProductCharacteristic", "Value", "Valeur de la caracteristique"),
    ("IncludedNote", "Content", "Note"),
    ("SpecifiedLineTradeDelivery", "BilledQuantity", "Quantite"),
    ("NetPriceProductTradePrice", "ChargeAmount", "P.U. HT"),
    ("GrossPriceProductTradePrice", "ChargeAmount", "P.U. TTC"),
    ("AppliedTradeAllowanceCharge", "ActualAmount", "Frais / remise"),
    ("SpecifiedTradeSettlementLineMonetarySummation", "LineTotalAmount", "Total de la ligne (HT)"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "LineTotalAmount", "Total des lignes (HT)"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "TaxBasisTotalAmount", "Total HT"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "TaxTotalAmount", "Montant de TVA"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "GrandTotalAmount", "Total TTC"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "TotalPrepaidAmount", "Montant prepaye"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "DuePayableAmount", "Montant a payer"),
    ("SpecifiedTradeSettlementHeaderMonetarySummation", "RoundingAmount", "Arrondi"),
    ("SpecifiedTradeSettlementPaymentMeans", "TypeCode", "Mode de paiement"),
    ("SpecifiedTradeSettlementPaymentMeans", "Information", "Information paiement"),
    ("PayeePartyCreditorFinancialAccount", "IBANID", "IBAN"),
    ("PayeePartyCreditorFinancialAccount", "AccountName", "Titre du compte"),
    ("PayeeSpecifiedCreditorFinancialInstitution", "BICID", "BIC"),
    ("SellerTradeParty", "Name", "Raison sociale (vendeur)"),
    ("BuyerTradeParty", "Name", "Raison sociale (acheteur)"),
    ("PostalTradeAddress", "PostcodeCode", "Code postal"),
    ("ApplicableHeaderTradeSettlement", "InvoiceCurrencyCode", "Devise de reglement"),
    ("ApplicableHeaderTradeSettlement", "CreditorReferenceID", "Reference creditor"),
    ("SpecifiedTradePaymentTerms", "DirectDebitMandateID", "Mandat SEPA"),
];

pub const TITLES_GENERIC: &[(&str, &str)] = &[
    ("ID", "Identifiant"),
    ("Name", "Nom"),
    ("Note", "Note"),
    ("Percent", "Taux (%)"),
    ("Value", "Valeur"),
    ("Description", "Description"),
    ("TypeCode", "Code type"),
    ("Date", "Date"),
    ("Amount", "Montant"),
    ("Quantity", "Quantite"),
    ("CurrencyCode", "Devise"),
    ("StreetName", "Rue"),
    ("CityName", "Ville"),
    ("PostalZone", "Code postal"),
    ("CountryID", "Pays"),
    ("CountrySubentity", "Departement / Region"),
    ("ElectronicMail", "E-mail"),
    ("TelephoneNumber", "Telephone"),
    ("LineOne", "Rue"),
    ("Postcode", "Code postal"),
    ("CalculatedAmount", "Montant calcule"),
    ("ChargeAmount", "Montant"),
    ("RateApplicablePercent", "Taux (%)"),
    ("OccurrenceDateTime", "Date"),
    ("StartDateTime", "Debut"),
    ("EndDateTime", "Fin"),
    ("DueDateDateTime", "Echeance"),
    ("IssueDateTime", "Date d'emission"),
    ("SellerAssignedID", "Reference article"),
    ("BuyerAssignedID", "Reference article (acheteur)"),
    ("LineID", "N° de ligne"),
    ("LineExtensionAmount", "Total ligne"),
    ("InvoicedQuantity", "Quantite"),
    ("PriceAmount", "Prix"),
    ("BaseQuantity", "Base"),
    ("TaxableAmount", "Base"),
    ("TaxAmount", "Montant TVA"),
    ("PayableAmount", "A payer"),
    ("LineTotalAmount", "Total HT"),
    ("TotalAmount", "Total TTC"),
    ("DuePayableAmount", "A payer"),
    ("CustomizationID", "Norme"),
    ("ProfileID", "Profil"),
    ("IssueDate", "Date d'emission"),
    ("DueDate", "Echeance"),
    ("DocumentCurrencyCode", "Devise"),
    ("AccountingCost", "Ref. comptable"),
    ("PaymentMeansCode", "Mode de paiement"),
    ("PaymentID", "Ref. paiement"),
    ("CompanyID", "Identifiant societe"),
    ("RegistrationName", "Denomination legale"),
    ("IdentificationCode", "Pays"),
    ("EndpointID", "Identifiant emetteur"),
    ("ModelID", "Modele"),
    ("StandardID", "Code normalise"),
    ("CommodityCode", "Code douanier"),
    ("SequenceNumeric", "Sequence"),
    ("AllowanceReason", "Motif remise"),
    ("ChargeReason", "Motif majoration"),
    ("RatePercent", "Taux (%)"),
    ("AllowanceAmount", "Montant remise"),
    ("PrepaidAmount", "Prepaye"),
    ("PayableRoundingAmount", "Arrondi"),
    ("TaxInclusiveAmount", "Total TTC"),
    ("TaxExclusiveAmount", "Total HT"),
    ("LineCountNumeric", "Nombre de lignes"),
    ("BilledQuantity", "Quantite"),
    ("IBANID", "IBAN"),
    ("BICID", "BIC"),
    ("AccountName", "Titre du compte"),
    ("CreditorReferenceID", "Reference creditor"),
    ("DirectDebitMandateID", "Mandat SEPA"),
    ("GlobalID", "Identifiant global"),
    ("URIID", "URI"),
    ("Information", "Information"),
    ("ActualAmount", "Montant"),
    ("CategoryCode", "Categorie"),
    ("ChargeIndicator", "Frais ou remise"),
    ("Indicator", "Indicateur"),
    ("SubjectCode", "Code sujet"),
    ("DateTimeString", "Date"),
    ("GrandTotalAmount", "Total TTC"),
    ("TaxBasisTotalAmount", "Total HT"),
    ("TaxTotalAmount", "Montant TVA"),
    ("TotalPrepaidAmount", "Montant prepaye"),
    ("RoundingAmount", "Arrondi"),
    ("BasisAmount", "Base"),
    ("InvoiceCurrencyCode", "Devise"),
    ("PostcodeCode", "Code postal"),
    ("PersonName", "Nom du contact"),
    ("DueDateTypeCode", "Type echeance"),
];
